### ISSUE TITLE
Prepare update for Turing v0.35

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/docs#541]
## TODO (in this order)

 - [x] Release Turing ~~0.35.0~~ we're at 0.35.2 now
 - [x] Bump min Julia version on intro page
 - ~~Verify that changelog is updated~~ (Can't do this until it's merged)
 - [x] https://github.com/TuringLang/docs/issues/521
 - [x] Get rid of any other mention of Tracker, add Mooncake where necessary
 - [x] Port #539
